/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */

import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "color-picker": colorPicker,
    graphql: graphql,
  },
});
